### PR TITLE
Add ELF parser to retrieve enclave symbol addresses

### PR DESCRIPTION
**Pull request by w-woloszyn**
A simple elf parser for retrieving enclave symbol addresses.

### CODE REVIEW

**Comment by w-woloszyn** [comment]
It requires gelf.h, which is in the libelf-dev package I believe. CI failed due to the lack of that package.

**Comment by jovanbulck** [comment]
this is great! Thank you @w-woloszyn for the contribution, which will indeed greatly facilitate attack prototyping :)

linking long-standing issue: #22 

I'll have a look at updating the CI environment and testing this so it can be merged :+1:

**Comment by w-woloszyn** [comment]
Glad you like it! Let me know how the testing goes. If everything goes okay, I am happy to integrate the rest of the examples in the app folder :)

**Comment by jovanbulck** [comment]
Excellent, that'd be great!

I suggest to make the following changes:

* add the `libelf-dev` package to the install script [here](https://github.com/jovanbulck/sgx-step/blob/1856d6bbfe61c45b04ba20aeb41dd1dee29c9c6a/sdk/intel-sdk/install_SGX_SDK.sh#L32) -- that should normally suffice to fix the error message in the CI :crossed_fingers: 
* remove `void add_symbol(const char *name, uintptr_t address);` from the header file as it probably should be an internal function only and shouldn't be exposed (maybe consider making it `static` for that reason?)
* the repeated `elf_end; close; return` statements can probably be replaced with a `goto err` like in the Linux kernel coding conventions, but that's arguably a matter of taste ("goto considered harmful" :sweat_smile: ), so feel free to change or keep it as you prefer for the PR and I should probably do a global style unification of the code anyway at some later point
* ideally, integration with the other examples, where possible

**Comment by w-woloszyn** [comment]
All done. I couldn't test the app/bench though :( For some reason my Ubuntu freezes when running it (even before the changes).

**Comment by jovanbulck** [comment]
Merged, thank you for the great contribution @w-woloszyn !

Closes #22

**Pull request merged**
